version: '3'

services:
  app:
    image: app
    build:
      context: ./Web.Api
      dockerfile: Dockerfile
    ports:
      - 5000:80
  prometheus: 
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
  grafana: 
    image: grafana/grafana
    ports:
      - 3000:3000